Feature modmenu
calniotrey/space-corp pull request #65
Opened 2021-03-23 20:20 UTC by fireinthedisco

Still need to do the iisc_paused/iisc_stopped stuff, as well as make sure that the other settings are affecting the right pieces to selectively disable features

2021-03-23 20:39 UTC, fireinthedisco commented on events/iisc_pulse_events.txt
> +		every_country = {
I'm not sure what's going on here, this might have to do with the change I merged in.

2021-03-23 20:40 UTC, fireinthedisco commented on events/iisc_start_events.txt
> +
This is triggered by game start, but we may also need to set these/have these triggered when the mod is added to an ongoing game.

2021-03-23 20:43 UTC, fireinthedisco commented on common/scripted_effects/iisc_science_ship_effects.txt
> +				}
This looks like a mess, but all I did was add an if statement surrounded everything in the trigger requiring there to be the right flags present :|

2021-03-30 22:10 UTC, calniotrey commented
[containerwindow.cpp:814]: interface/iisc_modmenu_interface.gui: Could not find buttonType "option_button" in window "iisc_modmenu_status_text_running".
[containerwindow.cpp:814]: interface/iisc_modmenu_interface.gui: Could not find buttonType "option_button" in window "iisc_modmenu_status_text_paused".
[containerwindow.cpp:814]: interface/iisc_modmenu_interface.gui: Could not find buttonType "option_button" in window "iisc_modmenu_status_text_stopped_timer".

Maybe put a hidden button?

2021-03-30 22:12 UTC, calniotrey requested changes

2021-03-30 22:12 UTC, calniotrey commented on common/scripted_triggers/iisc_hq_deposits_triggers.txt
> +			has_global_flag = iisc_hq_development_player
With a plural "s" right?

2021-03-30 22:12 UTC, calniotrey commented on common/scripted_triggers/iisc_triggers.txt
> +		has_global_flag = iisc_corp_mining_stations_all
iisc_mining_stations_all ?

2021-03-30 22:12 UTC, calniotrey commented on common/scripted_triggers/iisc_triggers.txt
> +		has_global_flag = iisc_corp_research_stations_all
iisc_research_stations_all

2021-03-30 22:12 UTC, calniotrey commented on common/scripted_triggers/iisc_triggers.txt
> +			has_global_flag = iisc_corp_convoys_player
iisc_corp_convoys_players

2021-03-30 22:20 UTC, calniotrey commented on common/scripted_effects/iisc_utility_effects.txt
> +				iisc_remove_hq_deposit_from_corp = yes
You need to load the HQ before using this effect

2021-03-31 23:28 UTC, fireinthedisco commented on events/iisc_start_events.txt
> +
Added!

2021-04-01 13:38 UTC, calniotrey approved these changes
Looks good!

2021-04-01 15:39 UTC, merged